MOD_HEADERS  := geo_data.h geo_io.h
MOD_SOURCES  := geo_data.cpp geo_io.cpp io_gpx.cpp io_kml.cpp io_gu.cpp io_ozi.cpp io_json.cpp
SIMPLE_TESTS := geo_data geo_dist ozi
PKG_CONFIG = 'libxml-2.0 jansson libzip'

include ../Makefile.inc
