MOD_HEADERS  := geo_data.h geo_io.h conv_geo.h geo_utils.h filters.h
MOD_SOURCES  := geo_data.cpp geo_io.cpp conv_geo.cpp geo_utils.cpp\
                io_gpx.cpp io_kml.cpp io_gu.cpp io_ozi.cpp io_json.cpp\
                filters.cpp

SIMPLE_TESTS := geo_data ozi conv_geo geo_utils
PKG_CONFIG = 'libxml-2.0 proj'

include ../Makefile.inc
