#!/bin/sh

# mapdb program
MAPDB=../../programs/ms2mapdb/ms2mapdb

# download vmap files if needed
[ -f n37-030.vmap ] ||
  wget https://raw.githubusercontent.com/slazav/map_podm/master/vmap/n37-030.vmap
[ -f n49-032.vmap ] ||
  wget https://raw.githubusercontent.com/slazav/map_hr/master/vmap/n49-032.vmap

# make pics if needed
make -C pics

# remove old databases
$MAPDB delete .

# create map
$MAPDB create .

name=n49-032
dpi=100

# import vmap file
$MAPDB import_vmap . $name.vmap --config import_vmap.cfg

# render, result is 8-bit PNG + map
time $MAPDB render . --out $name.png --config render.cfg\
   --mkref nom --name $name --dpi $dpi --margin 10\
   --cmap_color 255 --png_format pal\
   --map $name.map

# remove old databases
$MAPDB delete .

# create map
$MAPDB create .

name=n37-030
dpi=200

# import vmap file
$MAPDB import_vmap . $name.vmap --config import_vmap.cfg

# render
time $MAPDB render . --out $name.png --config render.cfg\
   --mkref nom --name $name --dpi $dpi --margin 10\
   --cmap_color 255 --png_format pal\
   --map $name.map

$MAPDB delete .
