MOD_HEADERS  := point.h line.h multiline.h rect.h line_walker.h
MOD_SOURCES  := json_pt.cpp line_walker.cpp
SIMPLE_TESTS := point2d point3d line2d line3d multiline rect line_walker
PKG_CONFIG   := jansson

include ../Makefile.inc
