MOD_HEADERS  := point.h line.h multiline.h rect.h line_walker.h poly_tools.h
MOD_SOURCES  := json_pt.cpp line_walker.cpp
SIMPLE_TESTS := point line multiline rect line_walker poly_tools
PKG_CONFIG   := jansson

include ../Makefile.inc
