MOD_HEADERS  := gobj_test_grid.h gobj_test_tile.h

MOD_SOURCES  := gobj_test_grid.cpp gobj_test_tile.cpp

PKG_CONFIG = 'glibmm-2.4 gtkmm-2.4 gthread-2.0'

PROGRAMS := simple_tiles simple_grid\
            dthread_tiles dthread_grid\
            simple_rubb1 simple_rubb2 action1 action2 action3\
            all_viewers two_rubbers dthread_rubb1

MODDIR   := ../../modules
include $(MODDIR)/Makefile.inc

