MOD_HEADERS  := gobj_trk.h   gobj_wpts.h   gobj_maps.h   draw_pulk_grid.h
MOD_SOURCES  := gobj_trk.cpp gobj_wpts.cpp gobj_maps.cpp draw_pulk_grid.cpp
SCRIPT_TESTS := draw_trk

include ../Makefile.inc
