MOD_HEADERS := gobj_trk.h gobj_wpts.h gobj_maps.h\
               draw_pulk_grid.h write_geoimg.h

MOD_SOURCES := gobj_trk.cpp gobj_wpts.cpp gobj_maps.cpp\
                draw_pulk_grid.cpp write_geoimg.cpp

SCRIPT_TESTS := draw_trk

include ../Makefile.inc
