# Input/output functions for mapsoft.
# Should work with all supported data formats.

MOD_HEADERS  := tmpdir.h
MOD_SOURCES  := tmpdir.cpp
SCRIPT_TESTS := tmpdir

PKG_CONFIG   := libzip

include ../Makefile.inc
