MOD_HEADERS := image.h image_colors.h\
               image_gif.h image_jpeg.h image_png.h image_tiff.h\
               image_io.h

MOD_SOURCES := image.cpp image_colors.cpp\
               image_gif.cpp image_jpeg.cpp image_png.cpp image_tiff.cpp\
               image_io.cpp

SIMPLE_TESTS := image image_colors\
                image_gif image_jpeg image_png image_tiff\
                image_reduce image_io

PKG_CONFIG := libgif libjpeg libpng libtiff-4

include ../Makefile.inc
