# https://github.com/lyokato/libgeohash/blob/master/tests/geohash_test.c

MOD_HEADERS  := geohash.h storage.h
MOD_SOURCES  := geohash.cpp storage.cpp
SIMPLE_TESTS := geohash storage
PROGRAMS := print_hash
include ../Makefile.inc
