MOD_HEADERS  := rubber.h gobj.h gobj_multi.h\
                simple_viewer.h dthread_viewer.h\
                gobj_solid_fill.h

MOD_SOURCES  :=  rubber.cpp gobj.cpp\
                simple_viewer.cpp dthread_viewer.cpp\
                action_manager.cpp\
                gobj_solid_fill.cpp

PKG_CONFIG = 'gtkmm-3.0 gthread-2.0'

include ../Makefile.inc

