MOD_HEADERS  := image_gdk.h viewer.h rubber.h gobj.h\
                simple_viewer.h dthread_viewer.h\
                gobj_solid_fill.h

MOD_SOURCES  :=  rubber.cpp gobj.cpp\
                simple_viewer.cpp dthread_viewer.cpp\
                action_manager.cpp\
                gobj_solid_fill.cpp

PKG_CONFIG = 'glibmm-2.4 gtkmm-2.4 gthread-2.0'

include ../Makefile.inc

