PROGRAMS := ms2vmapdb

 OTHER_TESTS :=\
   test_interface\
   test_obj\
   test_convert\
   test_update_labels\
   test_crop\
   test_mkpt\

MODDIR      := ../../modules
include $(MODDIR)/Makefile.inc
