#!/bin/bash -efu

# Add objects

P=${1:-./ms2vmapdb}

. ../../modules/test_lib.sh

TESTDIR=../ms2vmap/test_data
TYPES="$TESTDIR/types.cfg"

## n37-1 [35.9980506,53.9999122,3.00014007,2.00008037]

$P delete tmp
$P create tmp
$P add_obj tmp point:1 [34.0,55.0] --name Point1 >/dev/null # del
$P add_obj tmp point:1 [36.2,55.7] --name Point2 >/dev/null  # keep
$P add_obj tmp line:1  [[35.2,55.7],[36.3,55.2]] >/dev/null   # crop
$P add_obj tmp area:1  [[35,53],[35,55],[37,53]] >/dev/null   # crop

assert_cmd "$P crop_nom tmp n37-1" "" 0
assert_cmd "$P export tmp -o tmp.vmap2 -t $TYPES" "" 0
assert_diff test_data/cr1.vmap2 tmp.vmap2

assert_cmd "$P crop_rect tmp [35.9980506,53.9999122,3.00014007,2.00008037]" "" 0
assert_cmd "$P export tmp -o tmp.vmap2 -t $TYPES" "" 0
assert_diff test_data/cr1.vmap2 tmp.vmap2

assert_cmd "$P delete tmp" "" 0

