MOD_HEADERS := actions.h
MOD_SOURCES := action_mp.cpp

PROGRAMS := ms2vmap

OTHER_TESTS :=\
  ms2vmap.test1\
  ms2vmap.test2\
  ms2vmap.test3\


MODDIR      := ../../modules
include $(MODDIR)/Makefile.inc
