MOD_HEADERS := actions.h

PROGRAMS := ms2vmap

# OTHER_TESTS :=\
#   test_interface\
#   test_obj\
#   test_mp\
#   test_vmap\
#   test_render\


MODDIR      := ../../modules
include $(MODDIR)/Makefile.inc
