#!/bin/bash -efu

# General interface and option tests
# See also getopt module tests

P=${1:-./ms2vmap}

. ../../modules/test_lib.sh

rm -rf tmp.db

help_msg="$($P -h ||:)"
assert_cmd "$P" "Error: non-empty output file expected (use -o option)" 1
assert_cmd "$P --help" "$help_msg" 1
assert_cmd "$P --xxx " "Error: unknown option: --xxx" 1

assert_cmd "$P a" "Error: non-empty output file expected (use -o option)" 1
assert_cmd "$P --types nofile a -o b" "Error: can't open file: nofile" 1
assert_cmd "$P --types test_data/types.cfg a -o b" "Error: unsupported file extension: a" 1

