#!/bin/bash -efu

# VMAP and VMAP2 import/export

P=${1:-./ms2vmap}

. ../../modules/test_lib.sh

# vmap -> vmap2
assert_cmd "$P test_data/in.vmap -o tmp.vmap2 -t test_data/types.cfg" "" 0
assert_diff test_data/out.vmap2 tmp.vmap2

# vmap -> vmap (note that header is lost, this information is not supported in mapsoft2)
assert_cmd "$P test_data/in.vmap -o tmp.vmap -t test_data/types.cfg" "" 0
assert_diff test_data/out.vmap tmp.vmap

# vmap2 -> vmap2
assert_cmd "$P test_data/out.vmap2 -o tmp.vmap2 -t test_data/types.cfg" "" 0
assert_diff test_data/out.vmap2 tmp.vmap2

# vmap -> vmap
assert_cmd "$P test_data/out.vmap -o tmp.vmap -t test_data/types.cfg" "" 0
assert_diff test_data/out.vmap tmp.vmap

# vmap -> mp
assert_cmd "$P test_data/out.vmap -o tmp.mp -t test_data/types.cfg" "" 0
assert_diff test_data/out.mp tmp.mp

# mp -> vmap2 (labels lost)
assert_cmd "$P test_data/out.mp -o tmp.vmap2 -t test_data/types.cfg" "" 0
assert_diff test_data/out2.vmap2 tmp.vmap2

# mp -> vmap2, keep old labels
cp test_data/out.vmap2 tmp.vmap2
assert_cmd "$P test_data/out.mp -o tmp.vmap2
  -t test_data/types.cfg --keep_labels 1" "" 0
assert_diff test_data/out.vmap2 tmp.vmap2

# update source S1
cp test_data/out.vmap2 tmp.vmap2
assert_cmd "$P test_data/in_tags.vmap2 -o tmp.vmap2
  -t test_data/types.cfg --replace_source S1" "" 0
assert_diff test_data/out3.vmap2 tmp.vmap2

# vmap -> fig
cp test_data/in.fig tmp.fig
assert_cmd "$P test_data/in.vmap -o tmp.fig -t test_data/types.cfg" "" 0
assert_diff test_data/out.fig tmp.fig

## fig -> vmap2 (big rounding errors)
assert_cmd "$P test_data/out.fig -o tmp.vmap2 -t test_data/types.cfg" "" 0
assert_diff test_data/out4.vmap2 tmp.vmap2

# vmap -> vmap2 (fixing rounding errors)
cp test_data/out.vmap2 tmp.vmap2
assert_cmd "$P test_data/out.fig -o tmp.vmap2
   -t test_data/types.cfg --fix_rounding 1" "" 0
assert_diff test_data/out.vmap2 tmp.vmap2
