MOD_HEADERS := imgsrc.h image_gif.h image_jpeg.h image_png.h image_tiff.h
MOD_SOURCES := image_gif.cpp image_jpeg.cpp image_png.cpp image_tiff.cpp

SIMPLE_TESTS := image_gif image_jpeg image_png image_tiff image_reduce

PKG_CONFIG   := libgif libjpeg libpng libtiff-4

include ../Makefile.inc
