MOD_HEADERS  := io_gpx.h io_kml.h io_gu.h io_ozi.h io_json.h
MOD_SOURCES  := io_gpx.cpp io_kml.cpp io_gu.cpp io_ozi.cpp io_json.cpp
PKG_CONFIG = 'libxml-2.0 jansson'
SIMPLE_TESTS := ozi
include ../Makefile.inc
