#!/bin/sh -efu

prog=${1:-./catmp.test}

function do_test(){
  args=$1
  exp=$2
  res="$($prog $args 2>&1)" ||:
  if [ "$res" != "$exp" ]; then
    echo "ERROR at $prog $args: "
    echo "  args: \"$args\""
    echo "  exp:  \"$exp\""
    echo "  res:  \"$res\""
    return 1
  fi
  return 0
}

$prog test_data/f1.mp > tmp.mp
diff tmp.mp test_data/f1a.mp
rm tmp.mp

$prog test_data/f1.mp test_data/f11.mp  > tmp.mp
diff tmp.mp test_data/f11a.mp
rm tmp.mp

do_test 'test_data/f2.mp' 'Error: read_mp: wrong level number: [Level4=17]'
do_test 'test_data/f3.mp' 'Error: read_mp: Level3 should be less then Level2'
do_test 'test_data/f4.mp' 'Error: read_mp: Level3 should be less then Level2'
do_test 'test_data/f5.mp' 'Error: read_mp: wrong level number: [Data3=(55.666607,35.998067),(55.666599,35.498060)]'
do_test 'test_data/f6.mp' 'Error: read_mp: Levels setting 2..10 is expected: [Levels=12]'
do_test 'test_data/f7.mp' 'Error: read_mp: not all levels are set in the header'

exit 0

