#!/bin/sh

# mapsoft2 programs
MAPDB=../../programs/ms2vmapdb/ms2vmapdb
RENDER=../../programs/ms2render/ms2render
CONV=../../programs/ms2conv/ms2conv
PROJ=../../programs/ms2proj/ms2proj

# remove old databases
$MAPDB delete tmp

# create map
$MAPDB create tmp

# Pulkovo coordinates in km and without zone prefix:
area_m="[[0,0],[1,0],[1,3],[0,3]]"
line_m="[[0,0],[10,0],[10,3],[0,3]]"

# Convert coordinates to WGS,
# add object
for n in $(seq 0 10); do
  area_d=$($PROJ --shift [$n,0] --scale 1000 --from SU3 --to WGS $area_m)
  $MAPDB add_obj tmp area:$n "$area_d"
done

line_d=$($PROJ --shift [0,0] --scale 1000 --from SU3 --to WGS $line_m)
$MAPDB add_obj tmp line:1 "$line_d"

# render
for i in *.cfg; do
  echo "rendering $i"
  $RENDER tmp.vmap2db --out ${i%.cfg}.png --config $i\
   --mkref proj --coords_wgs $line_d --scale 1000 --dpi 300\
   --proj SU3 --margin 10
done

#$MAPDB export_vmap tmp a.vmap

$MAPDB delete tmp
