#!/bin/sh

# mapsoft2 programs
MAPDB=../../programs/ms2mapdb/ms2mapdb
CONV=../../programs/ms2conv/ms2conv
PROJ=../../programs/ms2proj/ms2proj

# remove old databases
$MAPDB delete .

# create map
$MAPDB create .

# Pulkovo coordinates in km and without zone prefix:
area_m="[[0,0],[1,0],[1,3],[0,3]]"
line_m="[[0,0],[10,0],[10,3],[0,3]]"

# Convert coordinates to WGS,
# add object
for n in $(seq 0 10); do
  area_d=$($PROJ --shift [$n,0] --scale 1000 --from SU3 --to WGS $area_m)
  $MAPDB add_obj . area:$n "$area_d"
done

line_d=$($PROJ --shift [0,0] --scale 1000 --from SU3 --to WGS $line_m)
$MAPDB add_obj . line:1 "$line_d"

# render
for i in 1 2 3 4; do
  $MAPDB render . --out render${i}.png --config render${i}.cfg\
   --mkref proj --coords_wgs $line_d --scale 1000 --dpi 300\
   --proj SU3 --margin 10
done

#$MAPDB export_vmap . a.vmap

$MAPDB delete .
