#!/bin/sh -eu

################################################
## Render map from mapdb database
## result is 8-bit PNG + map

# mapdb program
MAPDB=../../programs/ms2mapdb/ms2mapdb

name=n49-032
dpi=100

time $MAPDB render $name --out $name.png --config $name.cfg\
   --cmap_color 255 --cmap_save $name.cmap.png --cmap_add 0\
   --png_format pal --map $name.map


name=n37-030
dpi=200

# use multy-segment-track from border.gpx as a border
# fill background with dark-red color

time $MAPDB render $name --out $name.png --config $name.cfg\
   --cmap_color 255 --cmap_save $name.cmap.png --cmap_add 0\
   --map $name.map --border_file border.gpx --bgcolor 0xFF800000


