#!/bin/sh -eu

################################################
## Render map from mapdb database
## result is 8-bit PNG (colormap is taken from $name.cmap.png files)

# mapdb program
MAPDB=../../programs/ms2mapdb/ms2mapdb

name=n49-032

mkdir -p $name.tiles
rm -f $name.tiles/*

time $MAPDB render $name --config $name.cfg\
   --tmap --out "$name.tiles/map-{x}-{y}-{z}.png" --zmin 0 --zmax 12\
   --bgcolor 0 --png_format pal --cmap_load $name.cmap.png\
   --tmap_scale 1

name=n37-030

mkdir -p $name.tiles
rm -f $name.tiles/*

# use multy-segment-track from border.gpx as a border

time $MAPDB render $name --config $name.cfg\
   --tmap --out "$name.tiles/map-{x}-{y}-{z}.png" --zmin 9 --zmax 12\
   --bgcolor 0 --png_format pal --cmap_load $name.cmap.png\
   --border_file border.gpx\
   --tmap_scale 1

