#!/bin/sh -eu

################################################
## Render map from mapdb database
## result is 8-bit PNG (colormap is taken from $name.cmap.png files)

# P program
P=../../programs/ms2render/ms2render

rm -rf n49.tiles

# Example of imcremental tile generation. Multiple maps are rendered in the
# same tile set (--add option). Each map is clipped to its own border
# (see "nom_name" and "border_style" parameters in render.cfg), the
# whole set is clipped to the border from brd_n49.plt.
# Smaller tiles are created by rescaling large ones (--tmap_scale option)

for name in n49-{032,033}; do
time $P $name.vmap2db --config ../render.cfg\
   --define "{\"nom_name\":\"$name\", \"hr\":\"1\", \"border_style\":\"none\", \"dpi_val\":\"100\"}"\
   --tmap --add --out "n49.tiles/map-{z}/{x}-{y}.png" --zmin 9 --zmax 12\
   --bgcolor 0 --png_format pal --cmap_load $name.cmap.png\
   --border_file brd_n49.plt\
   --tmap_scale 1
done

name=n37-030
rm -rf $name.tiles

# use multy-segment-track from border.gpx as a border

time $P render.vmap2db $name --config ../render.cfg\
   --define "{\"nom_name\":\"$name\", \"hr\":\"0\", \"dpi_val\":\"200\"}"\
   --tmap --out "$name.tiles/map-{z}/{x}-{y}.png" --zmin 9 --zmax 12\
   --bgcolor 0 --png_format pal --cmap_load $name.cmap.png\
   --border_file brd_n37.gpx\
   --tmap_scale 1

