#!/bin/sh -eu

################################################
## Download example maps, create vmap2 databases and text files


P=../../programs/ms2vmap/ms2vmap

# download vmap files if needed
[ -f n37-030.vmap ] ||
  wget https://raw.githubusercontent.com/slazav/map_podm/master/vmap/n37-030.vmap
[ -f n49-032.vmap ] ||
  wget https://raw.githubusercontent.com/slazav/map_hr/master/vmap/n49-032.vmap
[ -f n49-033.vmap ] ||
  wget https://raw.githubusercontent.com/slazav/map_hr/master/vmap/n49-033.vmap

# make pics if needed
make -C ../pics

for name in n37-030 n49-032 n49-033; do

  # remove old database
  $P db_delete $name

  # create map
  $P db_create $name

  # import vmap file
  $P db_import $name.vmap -o $name -t ../types.cfg

  # convert to vmap2 text format
  $P convert $name.vmap -o $name.vmap2 -t ../types.cfg

done
