MOD_HEADERS := shp.h dbf.h db_tools.h db_geohash.h db_simple.h
MOD_SOURCES := shp.cpp dbf.cpp db_tools.cpp db_geohash.cpp db_simple.cpp

SIMPLE_TESTS := shp dbf db_geohash db_simple
PKG_CONFIG := shapelib jansson
LDLIBS += -ldb

include ../Makefile.inc
