MOD_HEADERS := db_tools.h db_geohash.h db_simple.h\
               mapdb.h
MOD_SOURCES := db_tools.cpp db_geohash.cpp db_simple.cpp string_pack.cpp\
               mapdb.cpp mapdb_vmap.cpp mapdb_mp.cpp

SIMPLE_TESTS := db_geohash db_simple string_pack\
                mapdb
PKG_CONFIG = 'libdb'

include ../Makefile.inc
