#!/bin/sh

# mapsoft2 programs
MAPDB=../../programs/ms2mapdb/ms2mapdb
CONV=../../programs/ms2conv/ms2conv
PROJ=../../programs/ms2proj/ms2proj

# remove old databases
$MAPDB delete .

# create map
$MAPDB create .

# Add object to MapDB in cwd.
# Arguments:
# - type (line:1, etc.)
# - coordinates in SU3 km, shifted 300 km from zone center (note 1200km prefix)
#   to have difference between geographic north and map vertical lines.
# - additional arguments to ms2mapdb
function add_obj {
  type="$1"; shift
  crd_km="$1"; shift
  #convert to degrees
  crd_deg=$($PROJ --shift [1200,5000] --scale 1000 --from SU3 --to WGS $crd_km)
  $MAPDB add_obj . "$type" "$crd_deg" "$@"
}

add_obj line:1 "[[0.1,0.05],[2.1,0.35]]"
add_obj area:1 "[[0,0],[2.1,0],[2.1,0.5],[0,0.5]]"

# first point: angle is not set
add_obj point:1 "[0.3,0.25]"
add_obj text:1  "[0.3,0.35]" --name "point 1"

# second point: angle is set to 0
add_obj point:1 "[1.0,0.25]"  --angle 0
add_obj text:1   "[1.0,0.35]" --angle 0 --name "point 2"

# 3rd point: angle is set to 20 degrees
add_obj point:1  "[1.7,0.25]" --angle 20
add_obj text:1   "[1.7,0.35]" --angle 20 --name "point 3"

crd_deg=$($PROJ --shift [1200,5000] --scale 1000 --from SU3 --to WGS [[0,0],[2.1,0.5]])

# render
for i in $(seq -w 1 5); do
  $MAPDB render . --out render${i}.png --config render${i}.cfg\
   --mkref proj --coords_wgs $crd_deg --scale 1000 --dpi 300\
   --proj SU3 --margin 10
done

#$MAPDB export_vmap . a.vmap

$MAPDB delete .
