MOD_SOURCES := cairo_wrapper.cpp
MOD_HEADERS := cairo_wrapper.h

SCRIPT_TESTS := cairo1
PKG_CONFIG := glibmm-2.4 gtkmm-2.4 gthread-2.0\
              cairomm-1.0 pixman-1 cairomm-ft-1.0

include ../Makefile.inc

