HEADERS := point.h line.h multiline.h rect.h line_walker.h
SOURCES := json_pt.cpp line_walker.cpp
SIMPLE_TESTS := point2d point3d line2d line3d multiline rect line_walker
LDLIBS += -ljansson

include ../Makefile.module
