#!/bin/sh -efu

prog=${1:-./read_words.test}

function assert(){
  res="$1"
  exp="$2"
  if [ "$res" != "$exp" ]; then
    printf "ERROR:\n"
    printf "  exp:  %s\n" "$exp"
    printf "  res:  %s\n" "$res"
    return 1
  fi
  return 0
}

assert "$(cat read_words.test_data1 | "$prog")" \
"$(cat <<EOF
 [a] [#] [b] [c] [ a' s ]
 [d] [e] [f] [ a' s]
 [\]
 [abc
def]
 [aa] [bb] [cc""dd''ee]
EOF
)"


assert "$(cat read_words.test_data2 | "$prog")" \
"$(cat <<EOF
 [a] [b "C" d] [e e]
 [a] [b 'C' d] [e	e]
EOF
)"


