#!/bin/sh -efu

prog=${1:-./read_words.test}

function assert(){
  res="$1"
  exp="$2"
  if [ "$res" != "$exp" ]; then
    printf "ERROR:\n"
    printf "  exp:  %s\n" "$exp"
    printf "  res:  %s\n" "$res"
    return 1
  fi
  return 0
}


assert "$("$prog" <<EOF
a \# b c " a\' s " # aa
d e f " a\' s"
\\\\

#
abc\\
def
aa bb "cc\"\"dd\'\'ee"
EOF)" \
"$(cat <<EOF
 [a] [#] [b] [c] [ a' s ]
 [d] [e] [f] [ a' s]
 [\]
 [abc
def]
 [aa] [bb] [cc""dd''ee]
EOF)"


assert "$("$prog" <<EOF
a 'b "C" d' e\ e# aa
a "b 'C' d" e\	e# aa
EOF)" \
"$(cat <<EOF
 [a] [b "C" d] [e e]
 [a] [b 'C' d] [e	e]
EOF)"

