#!/bin/sh -efu

prog=${1:-./read_words.test}

function assert(){
  res="$1"
  exp="$2"
  if [ "$res" != "$exp" ]; then
    printf "ERROR:\n"
    printf "  exp:  %s\n" "$exp"
    printf "  res:  %s\n" "$res"
    return 1
  fi
  return 0
}

assert "$(cat read_words.test_data1 | "$prog")" \
"$(cat <<EOF
1: [a] [#] [ABc] [aBC] [ a' s ]
2: [d] [e] [f] [ a' s]
3: [\]
6: [abc
def]
8: [aa] [bb] [cc""dd''ee]
EOF
)"

# same with lowercase option
assert "$(cat read_words.test_data1 | "$prog" -l)" \
"$(cat <<EOF
1: [a] [#] [abc] [abc] [ a' s ]
2: [d] [e] [f] [ a' s]
3: [\]
6: [abc
def]
8: [aa] [bb] [cc""dd''ee]
EOF
)"



assert "$(cat read_words.test_data2 | "$prog")" \
"$(cat <<EOF
1: [a] [b "C" d] [e e]
2: [a] [b 'C' d] [e	e]
3: [a
b
c
]
7: [a
b
c]
EOF
)"

assert "$(echo -e "#a\n\n\"b\n\nc" | "$prog" 2>&1)" \
"Error: Unclosed quote in line 3"


