#!/bin/bash -efu

# General interface and option tests
# See also getopt module tests

P=${1:-./ms2mapdb}

. ../../modules/test_lib.sh

rm -rf tmp.db

help_msg="$($P -h ||:)"
assert_cmd "$P" "$help_msg" 1
assert_cmd "$P --help" "$help_msg" 1
assert_cmd "$P --xxx " "Error: unknown option: --xxx" 1

assert_cmd "$P a" "Error: ms2mapdb: unknown action: a" 1
assert_cmd "$P a b" "Error: ms2mapdb: unknown action: a" 1

