#!/bin/bash -efu

# VMAP1 import/export

P=${1:-./ms2mapdb}

. ../../modules/test_lib.sh

rm -rf tmp.db

assert_cmd "$P import_vmap tmp.db" "Error: import_vmap: two arguments expected: MapDB folder, file name" 1
assert_cmd "$P import_vmap tmp.db missing.vmap" "Error: can't read VMAP file" 1

assert_cmd "$P import_vmap tmp.db test_data/n37-016.vmap" "" 0
assert_cmd "$P export_vmap tmp.db tmp.vmap" "" 0
assert_diff test_data/n37-016a.vmap tmp.vmap

rm -rf tmp.db

# importing with a config file:
assert_cmd "$P import_vmap tmp.db --config test_data/conf_vmap_imp.txt test_data/n37-016.vmap" "" 0
assert_cmd "$P export_vmap tmp.db --config test_data/conf_vmap_exp.txt tmp.vmap" "" 0
assert_diff test_data/n37-016b.vmap tmp.vmap

rm -rf tmp.db

# same but with command-line options
assert_cmd "$P import_vmap tmp.db --cnv_points [[\"0x900\",\"0x815\"],[0,0]] --cnv_lines [[4,0],[\"0xA\",0]] --cnv_areas=[[\"0x15\",\"0xFF00\"]] test_data/n37-016.vmap" "" 0
assert_cmd "$P export_vmap tmp.db --cnv_points [[\"0x815\",\"0x816\"],[0,0]] --cnv_areas=[[\"0xFF00\",\"0xFF01\"]] tmp.vmap" "" 0
assert_diff test_data/n37-016b.vmap tmp.vmap

rm -rf tmp.db
