#!/bin/bash -efu

# General interface and option tests
# See also getopt module tests

P=${1:-./ms2mapdb}

. ../test_lib.sh

rm -rf tmp.db

help_msg="$($P -h ||:)"
assert "$P" "$help_msg" 1
assert "$P --help" "$help_msg" 1
assert "$P --xxx " "Error: unknown option: --xxx" 1

assert "$P a" "Error: ms2mapdb: unknown action: a" 1
assert "$P a b" "Error: ms2mapdb: unknown action: a" 1

