#!/bin/bash -efu

# VMAP1 import/export

P=${1:-./ms2mapdb}

. ../../modules/test_lib.sh

rm -rf tmp.db

assert_cmd "$P import_vmap tmp.db" "Error: import_vmap: two arguments expected: MapDB folder, file name" 1
assert_cmd "$P import_vmap tmp.db missing.vmap" "Error: Can't find MapDB folder: tmp.db" 1

assert_cmd "$P create tmp.db" "" 0
assert_cmd "$P create tmp.db" "Error: db_simple: tmp.db/mapinfo.db: File exists" 1
assert_cmd "$P import_vmap tmp.db missing.vmap" "Error: can't read VMAP file" 1

assert_cmd "$P import_vmap tmp.db test_data/n37-016.vmap" "" 0
assert_cmd "$P export_vmap tmp.db tmp.vmap" "" 0
assert_diff test_data/n37-016a.vmap tmp.vmap

rm -rf tmp.db

# importing with a config file:
assert_cmd "$P create tmp.db" "" 0
assert_cmd "$P import_vmap tmp.db --config test_data/conf_vmap_imp.txt test_data/n37-016.vmap" "" 0
assert_cmd "$P export_vmap tmp.db --config test_data/conf_vmap_exp.txt tmp.vmap" "" 0
assert_diff test_data/n37-016b.vmap tmp.vmap

rm -rf tmp.db

