PROGRAMS    := ms2conv
OTHER_TESTS :=\
  ms2conv.test1\
  ms2conv.test2\
  ms2conv.test3\
  ms2conv.test4\
  ms2conv.test5\
  ms2conv.test6\
  ms2conv.test7\
  ms2conv.test_img\
  ms2conv.test_mkref

MODDIR := ../../modules
include $(MODDIR)/Makefile.inc


