PROGRAMS    := mapsoft
OTHER_TESTS :=\
  mapsoft.test1\
  mapsoft.test2\
  mapsoft.test3\
  mapsoft.test4\
  mapsoft.test5\
  mapsoft.test6\

MODDIR      := ../modules
include $(MODDIR)/Makefile.inc


