PROGRAMS    := mapsoft
OTHER_TESTS :=\
  mapsoft.test1\
  mapsoft.test2\
  mapsoft.test3\
  mapsoft.test4\
  mapsoft.test5

MODDIR      := ../modules

PKG_CONFIG  := libzip libxml-2.0 jansson

include $(MODDIR)/Makefile.inc


