MOD_SOURCES := conv_base.cpp conv_aff.cpp conv_geo.cpp
MOD_HEADERS := conv_base.h conv_aff.h conv_multi.h conv_geo.h

SIMPLE_TESTS := conv_base conv_aff conv_multi conv_geo
LDLIBS += -lproj -ljansson

include ../Makefile.inc
