#!/bin/bash -eu

# Pack all img files and typ into IMGMAP

##################################################

# read global configuration and functions
. vmaps.sh ||:

# read local configuration
. ./vmaps.conf ||:

if [ "$IMG_DIR" = "" ]; then
  echo "vmaps_pack_img: IMG_DIR is not set, exiting"
  exit
fi

if [ "$IMGMAP" = "" ]; then
  echo "vmaps_pack_img: IMGMAP is not set, exiting"
  exit
fi

##################################################

echo "Creating $IMGMAP"

typ=""
if [ -n "$TYPSRC" ]; then
  typ=TMP.TYP
  $CGPSM typ $TYPSRC $typ
fi

imgs=""
for vmap in $(list_vmaps); do
  imgs="$imgs $IMG_DIR/$(basename $vmap .$VMAP_EXT).img"
done

# Extract FID and codepage from TYPSRC
FID="$(sed -r -n '/\[_id\]/,/\[end\]/s/^ *FID=([0-9]+).*/\1/ip' "$TYPSRC")"
CP="$(sed -r -n '/\[_id\]/,/\[end\]/s/^ *CodePage=([0-9]+).*/\1/ip' "$TYPSRC")"
if [ "$FID" = "" ]; then
  echo "vmaps_pack_img: can't get FID from TYP file"
  exit
fi
if [ "$CP" = "" ]; then
  echo "vmaps_pack_img: can't get CodePage from TYP file"
  exit
fi

$GMT -j -v -m "$MAP_NAME" -f $FID,1 -o "$IMGMAP" $imgs $typ
$GMT -w -y $FID,1,$CP "$IMGMAP"

[ "$typ" = "" ] || rm -f "$typ"
