#!/bin/bash -eu

# Pack tiles into mbtiles database
# Based on script written by @ioctl
# Usage: make_sqlitedb <tile dir> <out file>
# Tile format: x-y-z.png, z/x-y.png

# see https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md

# read global configuration and functions
. vmaps.sh

# read local configuration
. ./vmaps.conf

# Remove output file if it exists
rm -f -- "$MBTILES"

# Create database
sqlite3 "$MBTILES" 'CREATE TABLE tiles (tile_column int, tile_row int,
  zoom_level int, tile_data blob,
  PRIMARY KEY (tile_column, tile_row, zoom_level));'
sqlite3 "$MBTILES" 'CREATE UNIQUE INDEX tile_index on tiles (zoom_level, tile_column, tile_row);'

# Find all tiles and put them into db
find -L "$TILE_DIR" -type f -name '*.png' | (
  echo 'PRAGMA journal_mode = OFF; PRAGMA synchronous = 0;'
  while read tile; do

    xyz="$(echo "$tile" | sed -rne '
      s|^.*/([0-9]+)-([0-9]+)-([0-9]+).*$|\1 \2 \3|p
      s|^.*/([0-9]+)/([0-9]+)-([0-9]+).*$|\2 \3 \1|p
    ')"
    read x y z <<< "$xyz"

    echo -n "INSERT INTO tiles (tile_column, tile_row, "
    echo -n "zoom_level, tile_data) VALUES "
    echo    "($x, $((2**z-1-y)), $z, readfile('$tile'));"
done )  | sqlite3 "$MBTILES"

# Create metadata table
ver=$(date +%Y-%m-%d)
sqlite3 "$MBTILES" "CREATE TABLE metadata (name text, value text);"
sqlite3 "$MBTILES" "INSERT INTO metadata (name, value) VALUES ('name',   '$MBTILES_NAME');"
sqlite3 "$MBTILES" "INSERT INTO metadata (name, value) VALUES ('attribution', '$MBTILES_ATTR');"
sqlite3 "$MBTILES" "INSERT INTO metadata (name, value) VALUES ('format', 'png');"
#sqlite3 "$MBTILES" "INSERT INTO metadata (name, value) VALUES ('bounds', '30.0,54,42,58');"
#sqlite3 "$MBTILES" "INSERT INTO metadata (name, value) VALUES ('center', '37.6,55.7,8');"
sqlite3 "$MBTILES" "INSERT INTO metadata (name, value) VALUES ('version', '$ver');"
sqlite3 "$MBTILES" "INSERT INTO metadata (name, value) VALUES ('type',    'overlay');"
sqlite3 "$MBTILES" "INSERT INTO metadata (name, value) VALUES ('minzoom', (SELECT min(zoom_level) FROM tiles));"
sqlite3 "$MBTILES" "INSERT INTO metadata (name, value) VALUES ('maxzoom', (SELECT max(zoom_level) FROM tiles));"
