#!/bin/sh -eu

# Make tiles
#
# Arguments: names with or without paths.
# No arguments: process all new vmap files
# Version for mapsoft2, 2024-11-07

##################################################

# read global configuration and functions
. vmaps.sh

# read local configuration
. ./vmaps.conf

##################################################

# Update colormap if needed
if [ ! -f "$CMAP" ]; then
  echo "Colormap is missing. Updating $CMAP"
  vmap_update_cmap $CMAP_SRC $CMAP
fi

##################################################
# If argument list is empty, find only old files
files=${@:-$(list_vmap_nt_tiles)}

# check that git is clean (print warnings, ignore result)
vmap_git_status_list $files ||:

##################################################
mkdir -p "$TILE_DIR"
for i in $files; do
  name=${i%.*}
  name=${name##*/}
  vmap="$VMAP_DIR/$name.$VMAP_EXT"
  if [ ! -f "$vmap" ]; then
    echo "can't find file: $vmap"
    continue
  fi

  # Loop through all regions (brd/<name>.gpx)
  for brd in $BRD_DIR/*.gpx; do

    $($MS2NOM --ext --name "$name" --cover "$brd") || continue

    # update tiles
    echo "Rendering tiles: $name"
    vmap_render_tiles "$name" "$brd"
  done
  touch "$TILE_DIR/$name.tstamp"
done

